baseURL: https://pascalmichaillat.org/hugo-website/
title: Achmad Rahman Mawardi
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
  tag: tags

menu:
  main:
    # - name: Books
    #   url: books/
    #   weight: 5
    # - name: Papers
    #   url: papers/
    #   weight: 2
    - name: Projects
      url: projects/
      weight: 1
    - name: Courses
      url: courses/
      weight: 3
    - name: Papers
      url: papers/
      weight: 4
    - name: Tags
      url: tags/
      weight: 5
    - name: LinkedIn
      url: https://www.linkedin.com/in/achmadrahman/
      weight: 6
    - name: GitHub
      url: https://github.com/achmadrahmanm
      weight: 7
    - name: FastWork
      url: https://fastwork.id/user/achmadrahmanm
      weight: 8

params:
  description: "Achmad Rahman Mawardi, Master of none"
  author: Achmad Rahman Mawardi
  # googleAnalyticsID: "G-XXXXX"
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: false
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["books", "courses", "papers", "data"]
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: "Achmad Rahman Mawardi"
    subtitle: "Iâ€™m a versatile Fullstack Developer with broad experience in building and managing mobile, web, and desktop applications across various industries. My work focuses on creating scalable and efficient digital solutions tailored to business needs."
    imageUrl: "foto_profile.png"
    imageWidth: 200
    imageHeight: 200
    imageStyle: "object-fit: cover;"

    buttons:
      # - name: Data
      #   url: data/
      # - name: Books
      #   url: books/
      - name: Projects
        url: projects/
      - name: Courses
        url: courses/
      - name: Papers
        url: papers/
      - name: Tags
        url: tags/
      # - name: Archive
      #   url: archive/
      - name: LinkedIn
        url: https://www.linkedin.com/in/achmadrahman/
      - name: GitHub
        url: https://github.com/achmadrahmanm
      - name: FastWork
        url: https://fastwork.id/user/achmadrahmanm

  socialIcons:
    - name: CV
      url: "Achmad Rahman Mawardi.pdf"
    - name: Email
      url: mailto:achmadrahmanm@gmail.com
    # - name: Zoom
    #   url: https://www.zoom.us/my/igelfeld
    - name: Location
      url: location/
    - name: Office Hours
      url: officehours/
    # - name: Google Scholar
    #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
    - name: GitHub
      url: https://github.com/achmadrahmanm
    # - name: Substack
    #   url: https://pmichaillat.substack.com
    # - name: YouTube
    #   url: https://www.youtube.com/@pmichaillat
    # - name: Twitter
    #   url: https://x.com/pmichaillat
    # - name: Bluesky
    #   url: https://bsky.app/profile/pmichaillat.bsky.social

  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Achmad Rahman Mawardi"
    icon: "favicon.ico"
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
